version: '3.9'


services:
  app:
    user: "root"
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
#      - ./data_base:/wd/data_base:rw
      - ./logs:/wd/logs:rw
    ports:
      - "5000:6000"
    command:
      - --host=0.0.0.0

