version: '3.9'


services:
  app:
    user: "1000:1000"
    userns_mode: "host"
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./data_base:/wd/data_base:rw
      - ./logs:/wd/logs:rw
    ports:
      - "5000:5000"
    command:
      - --host=0.0.0.0

