version: '3.9'


services:
  app:
    volumes:
      - ./files_input:/wd/files_input:ro
      - ./files_output:/wd/files_output:rw
      - ./data_base:/wd/data_base:ro
      - ./logs:/wd/logs:rw
    user: "1000"